# Generated by Django 4.1.3 on 2022-11-22 09:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to=api.models.filepathLogo)),
                ('bg', models.FileField(blank=True, null=True, upload_to=api.models.filepathBG)),
                ('qr', models.FileField(blank=True, null=True, upload_to=api.models.filepathQR)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
