# Generated by Django 4.1.3 on 2022-11-24 13:02

import brochure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to=brochure.models.filepathPDFLogo)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=brochure.models.filepathPDF)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
